export {
  generateEmbeddings,
  generateSingleEmbedding,
  validateEmbeddingDimension,
  calculateCost,
  type EmbeddingResult,
  type EmbeddingOptions,
  EMBEDDING_MODEL,
  EMBEDDING_DIMENSIONS,
  COST_PER_1K_TOKENS,
} from "./embeddings";

export {
  vectorSearch,
  insertCourseEmbedding,
  batchInsertEmbeddings,
  deleteCourseEmbedding,
  cosineSimilarity,
  euclideanDistance,
  type VectorSearchResult,
  type VectorSearchOptions,
} from "./vector";

export {
  findMatchingCourses,
  matchCourseToCatalog,
  getBestMatch,
  getConfidenceLevel,
  cosineSimilarity as matcherCosineSimilarity,
  type Course,
  type MatchResult,
  type MatcherOptions,
} from "./semantic-matcher";

export {
  convertCredits,
  batchConvertCredits,
  convertSemesterToQuarter,
  convertQuarterToSemester,
  convertECTSToSemester,
  normalizeInternationalCredits,
  applyInstitutionalRounding,
  applyRounding,
  findConversionRule,
  getAllConversionRules,
  getCreditSystemDescription,
  validateCreditValue,
  getConversionDocumentation,
  type CreditConversionResult,
  type CreditConversionRule,
  CreditSystem,
  RoundingMethod,
} from "./credit-conversion";

export {
  classifyCourse,
  classifyByDepartmentCode,
  classifyByKeywords,
  findKeywords,
  batchClassifyCourses,
  getFlaggedCourses,
  getDepartmentMappings,
  addDepartmentMapping,
  getKeywordMappings,
  validateSubjectArea,
  getSubjectAreaDescription,
  type SubjectClassificationResult,
  type DepartmentMapping,
  NCAASubjectArea,
} from "./subject-classification";

export {
  registerInstitution,
  getInstitution,
  getAllInstitutions,
  registerCourse,
  batchRegisterCourses,
  getCourse,
  getCourseByCode,
  getInstitutionCourses,
  searchCourses,
  createMapping,
  findMapping,
  findMappings,
  getMappingsForCourse,
  overrideMapping,
  deactivateMapping,
  getInstitutionLookup,
  queryCrossInstitution,
  getAllManualOverrides,
  getOverrideHistory,
  getStatistics,
  clearAllData,
  type Institution,
  type CourseRecord,
  type CourseMapping,
  type MappingQuery,
  type InstitutionLookupResult,
  type CrossInstitutionQuery,
  MappingType,
} from "./multi-institution-lookup";
